// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace CodeRetreat.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Evolving a living cell")]
    public partial class EvolvingALivingCellFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "01 - Live cells.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Evolving a living cell", "In order to create a functioning rules engine\r\nAs a programmer of Conway\'s Game o" +
                    "f Life\r\nI can evolve a single living cell", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Living cell with 0 neighbors dies")]
        public virtual void LivingCellWith0NeighborsDies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Living cell with 0 neighbors dies", ((string[])(null)));
#line 6
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table1.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
            table1.AddRow(new string[] {
                        ".",
                        "x",
                        "."});
            table1.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 7
    testRunner.Given("the following setup", ((string)(null)), table1);
#line 12
    testRunner.When("I evolve the board");
#line 13
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Living cell with 2 neighbors lives")]
        public virtual void LivingCellWith2NeighborsLives()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Living cell with 2 neighbors lives", ((string[])(null)));
#line 15
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table2.AddRow(new string[] {
                        ".",
                        "x",
                        "."});
            table2.AddRow(new string[] {
                        ".",
                        "x",
                        "x"});
            table2.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 16
    testRunner.Given("the following setup", ((string)(null)), table2);
#line 21
    testRunner.When("I evolve the board");
#line 22
    testRunner.Then("the center cell should be alive");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Living cell with 1 neighbor dies")]
        public virtual void LivingCellWith1NeighborDies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Living cell with 1 neighbor dies", ((string[])(null)));
#line 25
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table3.AddRow(new string[] {
                        ".",
                        "x",
                        "."});
            table3.AddRow(new string[] {
                        ".",
                        "x",
                        "."});
            table3.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 26
    testRunner.Given("the following setup", ((string)(null)), table3);
#line 31
    testRunner.When("I evolve the board");
#line 32
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Living cell with 3 neighbors lives")]
        public virtual void LivingCellWith3NeighborsLives()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Living cell with 3 neighbors lives", ((string[])(null)));
#line 34
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table4.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table4.AddRow(new string[] {
                        ".",
                        "x",
                        "."});
            table4.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 35
    testRunner.Given("the following setup", ((string)(null)), table4);
#line 40
    testRunner.When("I evolve the board");
#line 41
    testRunner.Then("the center cell should be alive");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Living cell with 4 neighbors dies")]
        public virtual void LivingCellWith4NeighborsDies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Living cell with 4 neighbors dies", ((string[])(null)));
#line 43
 this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table5.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table5.AddRow(new string[] {
                        ".",
                        "x",
                        "x"});
            table5.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 44
    testRunner.Given("the following setup", ((string)(null)), table5);
#line 49
    testRunner.When("I evolve the board");
#line 50
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Living cell with 5 neighbors dies")]
        public virtual void LivingCellWith5NeighborsDies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Living cell with 5 neighbors dies", ((string[])(null)));
#line 52
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table6.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table6.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table6.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 53
    testRunner.Given("the following setup", ((string)(null)), table6);
#line 58
    testRunner.When("I evolve the board");
#line 59
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Living cell with 6 neighbors dies")]
        public virtual void LivingCellWith6NeighborsDies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Living cell with 6 neighbors dies", ((string[])(null)));
#line 61
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table7.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table7.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table7.AddRow(new string[] {
                        "x",
                        ".",
                        "."});
#line 62
    testRunner.Given("the following setup", ((string)(null)), table7);
#line 67
    testRunner.When("I evolve the board");
#line 68
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Living cell with 7 neighbors dies")]
        public virtual void LivingCellWith7NeighborsDies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Living cell with 7 neighbors dies", ((string[])(null)));
#line 70
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table8.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table8.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table8.AddRow(new string[] {
                        "x",
                        "x",
                        "."});
#line 71
    testRunner.Given("the following setup", ((string)(null)), table8);
#line 76
    testRunner.When("I evolve the board");
#line 77
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Living cell with 8 neighbors dies")]
        public virtual void LivingCellWith8NeighborsDies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Living cell with 8 neighbors dies", ((string[])(null)));
#line 79
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table9.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table9.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table9.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
#line 80
    testRunner.Given("the following setup", ((string)(null)), table9);
#line 85
    testRunner.When("I evolve the board");
#line 86
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
