// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace CodeRetreat.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Evolving a dead cell")]
    public partial class EvolvingADeadCellFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "02 - Dead cell evolves.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Evolving a dead cell", "In order to create a functioning rules engine\r\nAs a programmer of Conway\'s Game o" +
                    "f Life\r\nI can evolve a single dead cell based", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dead cell with 0 neighbors stays dead")]
        public virtual void DeadCellWith0NeighborsStaysDead()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with 0 neighbors stays dead", ((string[])(null)));
#line 6
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table1.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
            table1.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
            table1.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 7
    testRunner.Given("the following setup", ((string)(null)), table1);
#line 12
    testRunner.When("I evolve the board");
#line 13
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dead cell with 1 neighbor stays dead")]
        public virtual void DeadCellWith1NeighborStaysDead()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with 1 neighbor stays dead", ((string[])(null)));
#line 15
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table2.AddRow(new string[] {
                        ".",
                        "x",
                        "."});
            table2.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
            table2.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 16
    testRunner.Given("the following setup", ((string)(null)), table2);
#line 21
    testRunner.When("I evolve the board");
#line 22
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dead cell with 2 neighbors stays dead")]
        public virtual void DeadCellWith2NeighborsStaysDead()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with 2 neighbors stays dead", ((string[])(null)));
#line 24
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table3.AddRow(new string[] {
                        ".",
                        "x",
                        "."});
            table3.AddRow(new string[] {
                        ".",
                        ".",
                        "x"});
            table3.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 25
    testRunner.Given("the following setup", ((string)(null)), table3);
#line 30
    testRunner.When("I evolve the board");
#line 31
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dead cell with 3 neighbors comes to life")]
        public virtual void DeadCellWith3NeighborsComesToLife()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with 3 neighbors comes to life", ((string[])(null)));
#line 33
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table4.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table4.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
            table4.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 34
    testRunner.Given("the following setup", ((string)(null)), table4);
#line 39
    testRunner.When("I evolve the board");
#line 40
    testRunner.Then("the center cell should be alive");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dead cell with 4 neighbors stays dead")]
        public virtual void DeadCellWith4NeighborsStaysDead()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with 4 neighbors stays dead", ((string[])(null)));
#line 42
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table5.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table5.AddRow(new string[] {
                        ".",
                        ".",
                        "x"});
            table5.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 43
    testRunner.Given("the following setup", ((string)(null)), table5);
#line 48
    testRunner.When("I evolve the board");
#line 49
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dead cell with 5 neighbors stays dead")]
        public virtual void DeadCellWith5NeighborsStaysDead()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with 5 neighbors stays dead", ((string[])(null)));
#line 51
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table6.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table6.AddRow(new string[] {
                        "x",
                        ".",
                        "x"});
            table6.AddRow(new string[] {
                        ".",
                        ".",
                        "."});
#line 52
    testRunner.Given("the following setup", ((string)(null)), table6);
#line 57
    testRunner.When("I evolve the board");
#line 58
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dead cell with 6 neighbors stays dead")]
        public virtual void DeadCellWith6NeighborsStaysDead()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with 6 neighbors stays dead", ((string[])(null)));
#line 60
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table7.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table7.AddRow(new string[] {
                        "x",
                        ".",
                        "x"});
            table7.AddRow(new string[] {
                        "x",
                        ".",
                        "."});
#line 61
    testRunner.Given("the following setup", ((string)(null)), table7);
#line 66
    testRunner.When("I evolve the board");
#line 67
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dead cell with 7 neighbors stays dead")]
        public virtual void DeadCellWith7NeighborsStaysDead()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with 7 neighbors stays dead", ((string[])(null)));
#line 69
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table8.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table8.AddRow(new string[] {
                        "x",
                        ".",
                        "x"});
            table8.AddRow(new string[] {
                        "x",
                        "x",
                        "."});
#line 70
    testRunner.Given("the following setup", ((string)(null)), table8);
#line 75
    testRunner.When("I evolve the board");
#line 76
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dead cell with 8 neighbors stays dead")]
        public virtual void DeadCellWith8NeighborsStaysDead()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dead cell with 8 neighbors stays dead", ((string[])(null)));
#line 78
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "*",
                        "*",
                        "*"});
            table9.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
            table9.AddRow(new string[] {
                        "x",
                        ".",
                        "x"});
            table9.AddRow(new string[] {
                        "x",
                        "x",
                        "x"});
#line 79
    testRunner.Given("the following setup", ((string)(null)), table9);
#line 84
    testRunner.When("I evolve the board");
#line 85
    testRunner.Then("the center cell should be dead");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
