// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace CodeRetreat.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Cell configurations that are static")]
    public partial class CellConfigurationsThatAreStaticFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "04 - Static structures.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Cell configurations that are static", "In order to create a functioning rules engine\r\nAs a programmer of Conway\'s Game o" +
                    "f Life\r\nI can see static structures surviving in my world", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Block")]
        public virtual void Block()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Block", ((string[])(null)));
#line 6
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
            table1.AddRow(new string[] {
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table1.AddRow(new string[] {
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table1.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
            table1.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
#line 7
    testRunner.Given("the following setup", ((string)(null)), table1);
#line 13
    testRunner.When("I evolve the board");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
            table2.AddRow(new string[] {
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table2.AddRow(new string[] {
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table2.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
            table2.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
#line 14
    testRunner.Then("I should see the following board", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Beehive")]
        public virtual void Beehive()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Beehive", ((string[])(null)));
#line 21
     this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
            table3.AddRow(new string[] {
                        ".",
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table3.AddRow(new string[] {
                        ".",
                        "x",
                        ".",
                        ".",
                        "x",
                        "."});
            table3.AddRow(new string[] {
                        ".",
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table3.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
#line 22
    testRunner.Given("the following setup", ((string)(null)), table3);
#line 28
    testRunner.When("I evolve the board");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
            table4.AddRow(new string[] {
                        ".",
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table4.AddRow(new string[] {
                        ".",
                        "x",
                        ".",
                        ".",
                        "x",
                        "."});
            table4.AddRow(new string[] {
                        ".",
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table4.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
#line 29
    testRunner.Then("I should see the following board", ((string)(null)), table4);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Loaf")]
        public virtual void Loaf()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Loaf", ((string[])(null)));
#line 36
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
            table5.AddRow(new string[] {
                        ".",
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table5.AddRow(new string[] {
                        ".",
                        "x",
                        ".",
                        ".",
                        "x",
                        "."});
            table5.AddRow(new string[] {
                        ".",
                        ".",
                        "x",
                        ".",
                        "x",
                        "."});
            table5.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        "x",
                        ".",
                        "."});
            table5.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
#line 37
    testRunner.Given("the following setup", ((string)(null)), table5);
#line 44
    testRunner.When("I evolve the board");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
            table6.AddRow(new string[] {
                        ".",
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table6.AddRow(new string[] {
                        ".",
                        "x",
                        ".",
                        ".",
                        "x",
                        "."});
            table6.AddRow(new string[] {
                        ".",
                        ".",
                        "x",
                        ".",
                        "x",
                        "."});
            table6.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        "x",
                        ".",
                        "."});
            table6.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
#line 45
    testRunner.Then("I should see the following board", ((string)(null)), table6);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Boat")]
        public virtual void Boat()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Boat", ((string[])(null)));
#line 53
  this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
            table7.AddRow(new string[] {
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table7.AddRow(new string[] {
                        ".",
                        "x",
                        ".",
                        "x",
                        "."});
            table7.AddRow(new string[] {
                        ".",
                        ".",
                        "x",
                        ".",
                        "."});
            table7.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
#line 54
    testRunner.Given("the following setup", ((string)(null)), table7);
#line 60
    testRunner.When("I evolve the board");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
            table8.AddRow(new string[] {
                        ".",
                        "x",
                        "x",
                        ".",
                        "."});
            table8.AddRow(new string[] {
                        ".",
                        "x",
                        ".",
                        "x",
                        "."});
            table8.AddRow(new string[] {
                        ".",
                        ".",
                        "x",
                        ".",
                        "."});
            table8.AddRow(new string[] {
                        ".",
                        ".",
                        ".",
                        ".",
                        "."});
#line 61
    testRunner.Then("I should see the following board", ((string)(null)), table8);
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
